productName = "Discord Fix GUI"
version = "0.1.0"
identifier = "com.fuderis.discord-fix-gui"

[build]
frontendDist = "ui"

[app]
withGlobalTauri = true

[[app.windows]]
url = "views/main.html"
title = "Discord Fix GUI"
width = 450
height = 650
resizable = true
fullscreen = false

[app.security]
csp = ""

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
resources = [
  "bin",
  "icon.ico",
  "icon2.ico"
]
